# Generated by Django 5.2.5 on 2025-09-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profile_profile_pic_profile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='mobile_num',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
