# Generated by Django 5.2.5 on 2025-09-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_address_profile_mobile_num_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_num',
        ),
    ]
