# Generated by Django 5.2.5 on 2025-09-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_products_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
