# Generated by Django 5.2.5 on 2025-09-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
