# Generated by Django 5.2.5 on 2025-09-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
