# Generated by Django 5.2.5 on 2025-09-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_location_transportation_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
    model_name='transportation',
    name='date_requested',
    field=models.DateTimeField(
        auto_now_add=True,
        default='2025-09-22 18:30:00'
    ),
    preserve_default=False,
)

    ]
