# Generated by Django 5.2.5 on 2025-09-23 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_transportation_date_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='payment',
            field=models.ImageField(blank=True, null=True, upload_to='payments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='transportation',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
