# Generated by Django 5.2.5 on 2025-09-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_transportation_payment_transportation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='passenger',
            field=models.TextField(blank=True, null=True),
        ),
    ]
