# Generated by Django 5.2.5 on 2025-09-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_transportation_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
