# Generated by Django 5.2.7 on 2025-12-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_message_chat_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.TextField(default='0'),
        ),
    ]
