# Generated by Django 5.2.7 on 2025-12-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
